export const DEFAULT_SITE_CONTENT = {
  hero: {
    tagline: '"Evoke the Ocean\'s Movement and Connection"',
    sub: "The UKZN Marine Life Club — where academic excellence meets coastal conservation, student advocacy, and scientific discovery along one of Africa's most biodiverse coastlines.",
  },
  about: {
    intro: 'The UKZN Marine Life Club exists to serve every marine biology student at the University of KwaZulu-Natal — providing community, resources, and a collective voice within the School of Life Sciences.',
    mission: 'To foster a community of passionate marine biology students at UKZN, providing academic support, professional development, and hands-on conservation experience while representing student interests.',
    vision: 'To become the premier student-led marine science organization in South Africa, recognized for excellence in research support, conservation impact, and student advocacy.',
    values: '<strong>Scientific Excellence:</strong> Rigorous academic standards<br><strong>Conservation Ethics:</strong> Protecting marine ecosystems<br><strong>Inclusivity:</strong> Welcoming all students<br><strong>Transparency:</strong> Open governance<br><strong>Innovation:</strong> New methodologies',
    presidentMessage: 'Welcome to the UKZN Marine Life Club. As we launch in 2025, we stand at the threshold of something remarkable. Our coastline is not just a research subject — it is our responsibility, our passion, and our future.',
  },
  contacts: {
    general: 'info@umlc.co.za',
    partnerships: 'partnerships@umlc.co.za',
    president: 'president@umlc.co.za',
  },
  socials: {
    instagram: 'https://instagram.com/ukzn_marine_life',
    tiktok: 'https://tiktok.com/@ukznmarinelife',
    facebook: 'https://facebook.com/ukznmarinelife',
    youtube: 'https://youtube.com/@ukznmarinelife',
  },
  footerAddress: 'UKZN Marine Life Club<br>School of Life Sciences<br>University of KwaZulu-Natal<br>Durban, South Africa',
  partnerIntro: 'Actively seeking collaborations with marine research institutions, conservation organizations, and industry partners.',
  bankDetails: {
    bank: 'First National Bank (FNB)',
    accName: 'UKZN Marine Life Club',
    accNum: '62894120843',
    branch: '250655',
  },
  seo: {
    enabled: true,
    title: 'UMLC — UKZN Marine Life Club | Empowering Future Marine Leaders',
    metaDesc: 'Official website of the UKZN Marine Life Club (UMLC). Discover academic support, marine conservation field projects, research conferences, and student voice.',
    canonical: 'https://www.umlc.co.za/',
  },
  sections: {
    home: true,
    about: true,
    species: true,
    programmes: true,
    'student-voice': true,
    events: true,
    partnerships: true,
    leadership: true,
  },
  settings: {
    animations: true,
    simpleNav: false,
    highContrast: false,
    sslBadge: true,
    loginLimit: true,
    cookieBanner: true,
  },
};

export const DEFAULT_PROGRAMMES = [
  {
    id: 1,
    num: '01',
    icon: 'academic',
    title: 'Academic Support',
    tagline: 'Your studies, amplified',
    summary: 'Peer tutoring, study groups, exam preparation workshops, and resource sharing for marine biology coursework.',
    description: "UMLC's Academic Support Programme ensures that no student falls behind. We connect senior students with first-years through structured tutoring sessions, provide access to past exam papers, facilitate study groups before major assessments, and host interactive workshops on challenging topics like marine taxonomy, oceanography, and ecological modeling.",
    activities: [
      'Weekly peer tutoring sessions for all marine biology modules',
      'Study group coordination for mid-terms and exams',
      'Shared digital resource library with past papers and notes',
      'Guest lectures from postgraduate researchers and alumni',
      'Academic writing workshops for lab reports and essays',
      'Module-specific WhatsApp groups for real-time support',
    ],
    howToJoin: 'Attend our weekly academic sessions or contact the Academic Officer via email. All registered UKZN marine biology students may participate for free.',
  },
  {
    id: 2,
    num: '02',
    icon: 'career',
    title: 'Professional Development',
    tagline: 'From student to scientist',
    summary: 'CV workshops, research methodology training, conference preparation, and industry networking events.',
    description: 'Bridging the gap between academic training and professional life. We run targeted workshops on research skills, scientific communication, industry exposure, and career preparation — giving UMLC members a competitive edge when they graduate.',
    activities: [
      'CV and cover letter writing workshops',
      'Research methodology and data analysis training',
      'Conference preparation and presentation coaching',
      'Industry site visits to marine research institutions',
      'Networking evenings with ORI, SAAMBR, and alumni professionals',
      'LinkedIn profile building and personal brand sessions',
    ],
    howToJoin: 'Sign up via the Student Voice form or email the VP directly. Sessions run once a month.',
  },
  {
    id: 3,
    num: '03',
    icon: 'conservation',
    title: 'Conservation Projects',
    tagline: 'Hands-on, ocean-first',
    summary: 'Beach clean-ups, marine species monitoring, and collaboration with local conservation organizations.',
    description: "Conservation is at the heart of UMLC. Through hands-on field projects, we give students the experience of working directly in KwaZulu-Natal's extraordinary marine ecosystems — from rocky intertidal zones to coral reefs and estuaries.",
    activities: [
      'Monthly beach clean-ups along the Durban coastline',
      'Marine species monitoring and citizen science surveys',
      'Collaboration with Ezemvelo KZN Wildlife and SAAMBR',
      'Turtle nesting site monitoring (seasonal)',
      'Underwater debris collection with certified dive team',
      'Annual coastal health report compiled by UMLC members',
    ],
    howToJoin: 'No experience needed. Join our conservation volunteer group — open to all UKZN students. Training is provided.',
  },
  {
    id: 4,
    num: '04',
    icon: 'research',
    title: 'Research & Conferences',
    tagline: 'Publish, present, lead',
    summary: 'Funding assistance for conference attendance, research presentation coaching, and journal clubs.',
    description: 'We actively support students who want to pursue research beyond their coursework. UMLC provides funding opportunities, coaching for conference presentations, and a regular journal club where cutting-edge marine research is discussed and critically reviewed.',
    activities: [
      'Journal club meetings — fortnightly research paper discussions',
      'Conference travel bursary applications support',
      'Research poster and oral presentation coaching',
      'Honours and MSc proposal writing workshops',
      'Collaboration facilitation with UKZN supervisors',
      'UMLC Annual Research Showcase for student projects',
    ],
    howToJoin: 'Contact the Research Officer or join a journal club session. Honours and postgraduate students especially welcome.',
  },
  {
    id: 5,
    num: '05',
    icon: 'events',
    title: 'Events Coordination',
    tagline: 'Building community',
    summary: 'Organising academic, social, and professional events that bring the UMLC community together throughout the year.',
    description: 'The Events Coordinator oversees all UMLC events — from intimate academic sessions to large-scale conservation drives and social gatherings. They work closely with all executive members to ensure every event runs smoothly, is well-attended, and creates lasting impact for members.',
    activities: [
      'Semester kickoff and orientation events for new members',
      'Marine Biology Quiz Nights and social mixers',
      'Annual UMLC Formal Dinner and Awards Evening',
      'Coordination with UKZN SRC for campus-wide events',
      'Logistics for field trips, workshops, and site visits',
      'Post-event feedback collection and improvement planning',
    ],
    howToJoin: 'Interested in helping run events? Volunteer with the Events Coordinator — all welcome!',
  },
];

export const DEFAULT_LEADERS = [
  {
    role: 'President',
    name: 'Siphamandla Mthembu',
    bio: 'Final year Marine Biology student passionate about estuarine ecology, shark conservation, and empowering student researchers across KwaZulu-Natal.',
    email: 'president@umlc.co.za',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
  },
  {
    role: 'Vice President',
    name: 'Dr. Anika Pillay',
    bio: 'Postgraduate marine ecologist focusing on coral reef resilience, ocean acidification, and coordinating university academic mentorship.',
    email: 'vicepresident@umlc.co.za',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
  },
  {
    role: 'Secretary',
    name: 'Thabo Dlamini',
    bio: 'Third-year BSc Biological Sciences. Oversees member registration, governance, meeting agendas, and executive correspondence.',
    email: 'secretary@umlc.co.za',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
  },
  {
    role: 'Treasurer',
    name: 'Liam van der Merwe',
    bio: 'Marine Sciences student with experience in non-profit financial administration, managing sponsorship bursaries, and field trip budgeting.',
    email: 'treasurer@umlc.co.za',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
  },
  {
    role: 'Media Officer',
    name: 'Zanele Khumalo',
    bio: 'Underwater photographer, scientific communicator, and manager of UMLC social media outreach and conservation awareness campaigns.',
    email: 'media@umlc.co.za',
    photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&q=80',
  },
  {
    role: 'Event Coordinator',
    name: 'Keanu Moodley',
    bio: 'Rescue diver and field enthusiast dedicated to curating impactful beach clean-ups, academic seminars, and coastal expeditions.',
    email: 'events@umlc.co.za',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
  },
];

export const DEFAULT_PARTNERS = [
  { slot: 1, name: 'SAAMBR', logo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=200&q=80', url: 'https://www.saambr.org.za' },
  { slot: 2, name: 'Oceanographic Research Institute', logo: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=200&q=80', url: 'https://www.ori.org.za' },
  { slot: 3, name: 'Ezemvelo KZN Wildlife', logo: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=200&q=80', url: 'http://www.kznwildlife.com' },
  { slot: 4, name: 'WildOceans Conservation', logo: 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?auto=format&fit=crop&w=200&q=80', url: 'https://wildtrust.co.za' },
];

export const DEFAULT_TIERS = [
  { slot: 1, icon: 'bronze', name: 'Supporter', price: 'R5,000', perks: 'Logo on website, social media acknowledgment, inclusion in annual club publication' },
  { slot: 2, icon: 'silver', name: 'Partner', price: 'R15,000', perks: 'All Supporter benefits + logo on event banners, priority recruitment access, guest lecture opportunity' },
  { slot: 3, icon: 'gold', name: 'Champion', price: 'R30,000+', perks: 'All Partner benefits + named student scholarship, exclusive excursion sponsorship, collaborative research showcase' },
];

export const DEFAULT_EVENTS = [
  {
    id: 1,
    title: 'Durban Coastline Beach Clean-up & Microplastics Survey',
    date: '2025-03-15',
    location: 'uShaka Beach / Point Waterfront, Durban',
    category: 'Conservation',
    description: 'Join UMLC members and ocean volunteers in our monthly coastal clean-up and citizen-science microplastics density audit along the Durban Golden Mile.',
    capacity: 50,
  },
  {
    id: 2,
    title: 'Marine Megafauna & Shark Conservation Seminar',
    date: '2025-03-27',
    location: 'UKZN Howard College, Life Sciences Auditorium',
    category: 'Academic',
    description: 'Distinguished guest seminar presented with KwaZulu-Natal Sharks Board and ORI researchers examining ragged-tooth shark telemetry along the South African eastern seaboard.',
    capacity: 80,
  },
  {
    id: 3,
    title: 'Aliwal Shoal Scuba & Snorkel Research Excursion',
    date: '2025-04-12',
    location: 'Umkomaas / Aliwal Shoal Marine Protected Area',
    category: 'Field Trip',
    description: 'Hands-on reef biodiversity assessment in one of the top dive sites on Earth. Student transport and chartered dive boat subsidized by UMLC.',
    capacity: 25,
  },
];
