export const SEARCH_INDEX = [
  { title: 'Home', section: '#home', desc: 'UMLC landing page, hero, and mission overview' },
  { title: 'About UMLC', section: '#about', desc: "Mission, vision, core values and president's launch message" },
  { title: 'Species Field Guide', section: '#species', desc: 'KwaZulu-Natal marine fauna, sharks, turtles, dolphins, and biodiversity' },
  { title: 'Academic Support', section: '#programmes', desc: 'Peer tutoring, study groups, past exam papers, and workshops' },
  { title: 'Professional Development', section: '#programmes', desc: 'CV workshops, research training, industry networking' },
  { title: 'Conservation Projects', section: '#programmes', desc: 'Monthly beach clean-ups, turtle monitoring, citizen science' },
  { title: 'Research & Conferences', section: '#programmes', desc: 'Journal clubs, conference coaching, bursaries, showcase' },
  { title: 'Events Coordination', section: '#programmes', desc: 'Club events, field trips, socials, orientation' },
  { title: 'Student Voice Tracker', section: '#student-voice', desc: 'Submit concerns anonymously and track live resolution progress' },
  { title: 'Events & Excursions', section: '#events', desc: 'Upcoming UMLC events, field trips, and RSVP registrations' },
  { title: 'Partnerships & Sponsors', section: '#partnerships', desc: 'Sponsorship tiers, collaborators, and proposal download' },
  { title: 'Executive Leadership', section: '#leadership', desc: 'Executive committee — President, VP, Secretary, Treasurer, Media Officer, Event Coordinator' },
  { title: 'Contact Us', section: '#leadership', desc: 'Club email channels and committee inquiries' },
];
